name: Deploy to Production

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: wp1-16531059-fa25  # Your Azure App Service name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Docker image to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ghcr.io/<your-github-username>/<your-image-name>:latest
